version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: carbumali-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carbumali_db
      MYSQL_USER: carbu_user
      MYSQL_PASSWORD: carbu_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - carbumali-network

  adminer:
    image: adminer
    container_name: carbumali-adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - carbumali-network

networks:
  carbumali-network:

volumes:
  mariadb_data:
